select * from 
jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
limit 100;

-- Revenue Generated by make vs female
select gender ,sum(purchase_amount) as revenue 
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
group by gender;

-- customers with discounts but more than average spend
select customer_id, purchase_amount
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
where discount_applied = "Yes" and purchase_amount >=(select avg (purchase_amount) from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed);

select avg(purchase_amount)
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed;

-- top 5 products with highest average rating
select item_purchased, round(AVG(review_rating),2) as Average_Rating
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- comparision between purchase amount in standard and express shipping
select shipping_type, avg(purchase_amount)
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
where shipping_type in ("Standard","Express")
group by shipping_type;

-- comparision subscription vs non subscription customers
select subscription_status, count(customer_id)as customers, round(avg(purchase_amount),2) as average_spend , sum(purchase_amount) as total_revenue
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
group by subscription_status;

-- segment customers into new returning and loyal
with customer_type as (
  select customer_id , previous_purchases,
  case 
      when previous_purchases = 1  then "New"
      when previous_purchases between 2 and 10 then "Returning"
      else "Loyal"
      end as customer_segment
  from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed

)

select customer_segment, count(*) as number_of_customers
from customer_type 
group by customer_segment;


-- What are the top 3 most purchased products within each category? 
with item_counts as (
    select category,
           item_purchased,
           count(customer_id) as total_orders,
           row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from jpmc-portfolio-project.customer_data.customer_shopping_behavior_processed
group by age_group
order by total_revenue desc;



